/// <reference types="next" />
/// <reference types="next/image-types/global" />

// This file is normally generated by Next.js. It is checked in here because
// the current environment cannot create files from package-manager/runtime commands.
